Update Run.bat
misterokaygo/D2RAssist pull request #48
Opened 2021-10-18 01:00 UTC by MazeEQ

2021-10-18 02:10 UTC, misterokaygo commented
We are close just a couple more things

2021-10-18 02:11 UTC, misterokaygo requested changes

2021-10-18 02:11 UTC, misterokaygo commented on D2MapApi/Run.bat
> +				for %%G in ("%InstallPath%") do if "%%~aG" Lss "d" if "%%~aG" GEq "-" (
is `Lss` case-sensitive?

2021-10-18 02:13 UTC, MazeEQ commented on D2MapApi/Run.bat
> +			for /f %%G in ('dir /b %~dp0..\*.exe') do ( start %~dp0..\%%G)
The space is required.

2021-10-19 13:55 UTC, AudriusButkevicius commented
This PR should also target develop branch I think, rather than main. If you are not very git proficient, might be easier to start from scratch making changes on that branch.

2021-10-20 00:46 UTC, OneXDeveloper requested changes
Please remove additional changes

2021-10-20 07:35 UTC, AudriusButkevicius approved these changes

2021-10-20 07:36 UTC, AudriusButkevicius commented
Actually, I'll just port your changes to a new PR.

2021-10-20 07:36 UTC, closed without merging